# Generated by Django 4.0.3 on 2022-03-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='plantimage',
            field=models.ImageField(upload_to='user_uploads/'),
        ),
    ]
