# Generated by Django 4.0.3 on 2022-03-23 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_post_plantimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_label', models.CharField(max_length=100)),
                ('post_prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.post')),
            ],
        ),
    ]
