# Generated by Django 4.0.3 on 2022-03-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_predictedplant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictedplant',
            options={'verbose_name_plural': 'Predicted Plants'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='plantimage',
            new_name='plant_image',
        ),
    ]
