# Generated by Django 4.0.3 on 2022-03-24 01:37

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_predictedplant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='plant_image',
            field=models.ImageField(default='', upload_to=users.models.get_upload_file_name),
        ),
    ]
