# Generated by Django 4.0.3 on 2022-03-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(default='Found at', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='plant_name',
            field=models.CharField(default='Known Plant Name in the Area', max_length=100),
        ),
    ]
