# Generated by Django 4.0.3 on 2022-03-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_post_city_alter_post_plant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='plant_name',
            field=models.CharField(default='Personal Identification', max_length=100),
        ),
    ]
