# Generated by Django 4.0.3 on 2022-03-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_post_plant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedplant',
            name='predicted_image',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictedplant',
            name='prediction_label',
            field=models.CharField(default='', max_length=100),
        ),
    ]
