# Generated by Django 4.0.3 on 2022-03-24 12:24

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_predictedplant_predicted_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='submitted',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(blank='False', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='plant_image',
            field=models.ImageField(default='', null='False', upload_to=users.models.get_upload_file_name),
        ),
        migrations.AlterField(
            model_name='predictedplant',
            name='predicted_image',
            field=models.CharField(blank='False', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictedplant',
            name='prediction_label',
            field=models.CharField(blank='False', default='', max_length=100),
        ),
    ]
