# Generated by Django 4.0.3 on 2022-03-24 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_post_submitted_alter_post_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(blank='True', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='predictedplant',
            name='predicted_image',
            field=models.CharField(blank='True', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='predictedplant',
            name='prediction_label',
            field=models.CharField(blank='True', default='', max_length=100),
        ),
    ]
