# Generated by Django 4.0.3 on 2022-03-28 03:41

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_predictedplant_latitude_predictedplant_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhilippinesCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_province', models.CharField(help_text='Where did you find it? City,Province', max_length=100, verbose_name='City Province')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(help_text='Where did you find it? City,Province', max_length=100, verbose_name='City Province'),
        ),
        migrations.AlterField(
            model_name='post',
            name='plant_image',
            field=models.ImageField(default='', upload_to=users.models.get_upload_file_name, verbose_name='Plant Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='plant_name',
            field=models.CharField(help_text='What do you think is the name of the plant?', max_length=100),
        ),
    ]
