# Generated by Django 4.0.3 on 2022-03-28 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_philippinescities_alter_post_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='philippinescities',
            options={'verbose_name_plural': 'PhilippinesCities'},
        ),
    ]
