# Generated by Django 4.0.3 on 2022-03-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_philippinescities_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(help_text='Where did you find it? City,Province', max_length=100),
        ),
    ]
