# Generated by Django 4.0.3 on 2022-03-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_post_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='philippinescities',
            options={'verbose_name_plural': 'Philippines Cities'},
        ),
    ]
