# Generated by Django 4.0.3 on 2022-03-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_post_plant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='plant_name',
        ),
    ]
