# Generated by Django 4.0.3 on 2022-03-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_post_plant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictedplant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='predictedplant',
            name='longitude',
        ),
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
