# Generated by Django 4.0.3 on 2022-03-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_post_plant_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhilippinesCities',
        ),
        migrations.RemoveField(
            model_name='post',
            name='plant_name',
        ),
    ]
