# Generated by Django 4.0.3 on 2022-03-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_delete_philippinescities_remove_post_plant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='city',
        ),
    ]
