# Generated by Django 4.0.3 on 2022-03-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_post_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plant_name',
            field=models.CharField(default='', help_text='What do you think is the name of the plant?', max_length=100),
        ),
    ]
