# Generated by Django 4.0.3 on 2022-03-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_post_plant_name_predictedplant_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='plant_name',
        ),
        migrations.RemoveField(
            model_name='predictedplant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='predictedplant',
            name='longitude',
        ),
    ]
