# Generated by Django 4.0.3 on 2022-03-31 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='post_pred_loc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.predictedplant'),
        ),
    ]
