# Generated by Django 4.0.3 on 2022-03-31 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_location_post_pred_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='post_loc',
        ),
        migrations.RemoveField(
            model_name='post',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='post',
            name='longitude',
        ),
    ]
