# Generated by Django 4.0.3 on 2022-03-31 11:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_remove_location_post_loc_remove_post_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='post_pred_loc',
        ),
        migrations.AddField(
            model_name='location',
            name='date_loc',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='post_loc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
    ]
