# Generated by Django 4.0.3 on 2022-03-31 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_remove_location_post_pred_loc_location_date_loc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
    ]
