# Generated by Django 4.0.3 on 2022-03-31 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_post_post_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='date_loc',
        ),
    ]
