# Generated by Django 4.0.3 on 2022-03-31 17:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_remove_location_date_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='date_loc',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
    ]
