# Generated by Django 4.0.3 on 2022-04-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_loc',
        ),
        migrations.AddField(
            model_name='post',
            name='post_lat',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='post_lng',
            field=models.CharField(default='', max_length=100),
        ),
    ]
