# Generated by Django 4.0.3 on 2022-04-04 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_location_post_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='post_loc',
        ),
        migrations.AddField(
            model_name='predictedplant',
            name='post_loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
        migrations.DeleteModel(
            name='CompleteInfo',
        ),
    ]
