<<<<<<< HEAD
# Generated by Django 3.2.7 on 2022-04-11 07:00
=======
# Generated by Django 4.0.3 on 2022-04-06 08:06
>>>>>>> c4cdfef43cd79a5a1e91e18e38a7f4c3f3656c67

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_location_matched_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='predicted_plant_label',
            field=models.CharField(default='', max_length=100),
        ),
    ]
