# Generated by Django 3.2.7 on 2022-04-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_location_matched_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='predicted_plant_label',
            field=models.CharField(default='', max_length=100),
        ),
    ]
