# Generated by Django 4.0.3 on 2022-03-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantsgallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(default='', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('plant_image', models.ImageField(default=None, upload_to='images')),
                ('pronounciation', models.TextField(default='-')),
                ('botany', models.TextField(default='-')),
                ('common_philippine_name1', models.CharField(blank=True, default='', max_length=200)),
                ('common_philippine_name2', models.CharField(blank=True, default='', max_length=200)),
                ('common_philippine_name3', models.CharField(blank=True, default='', max_length=200)),
                ('common_foreign_name1', models.CharField(blank=True, default='', max_length=200)),
                ('common_foreign_name2', models.CharField(blank=True, default='', max_length=200)),
                ('common_foreign_name3', models.CharField(blank=True, default='', max_length=200)),
                ('sci_philippine_name1', models.CharField(blank=True, default='', max_length=200)),
                ('sci_philippine_name2', models.CharField(blank=True, default='', max_length=200)),
                ('sci_philippine_name3', models.CharField(blank=True, default='', max_length=200)),
                ('sci_foreign_name1', models.CharField(blank=True, default='', max_length=200)),
                ('sci_foreign_name2', models.CharField(blank=True, default='', max_length=200)),
                ('sci_foreign_name3', models.CharField(blank=True, default='', max_length=200)),
                ('distribution', models.CharField(blank=True, default='', max_length=200)),
                ('conservation_status', models.TextField(default='-')),
                ('use_1', models.TextField(default='-')),
                ('use_2', models.TextField(blank=True, default='')),
                ('use_3', models.TextField(blank=True, default='')),
                ('scientific_studies1', models.TextField(default='-')),
                ('scientific_study_link1', models.TextField(blank=True, default='')),
                ('scientific_studies2', models.TextField(blank=True, default='')),
                ('scientific_study_link2', models.TextField(blank=True, default='')),
                ('scientific_studies3', models.TextField(blank=True, default='')),
                ('scientific_study_link3', models.TextField(blank=True, default='')),
                ('light_preference', models.TextField(blank=True, default='')),
                ('water_preference', models.TextField(blank=True, default='')),
                ('propagation_method', models.TextField(blank=True, default='')),
                ('references', models.TextField(blank=True, default='')),
                ('gallery_slider_1_image1', models.ImageField(default='-', upload_to='gallery image')),
                ('gallery_slider_1_image2', models.ImageField(default='-', upload_to='gallery image')),
                ('gallery_slider_1_image3', models.ImageField(default='-', upload_to='gallery image')),
                ('gallery_slider_2_image1', models.ImageField(default='-', upload_to='gallery image')),
                ('gallery_slider_2_image2', models.ImageField(default='-', upload_to='gallery image')),
                ('gallery_slider_2_image3', models.ImageField(default='-', upload_to='gallery image')),
            ],
        ),
    ]
