# Generated by Django 4.0.3 on 2022-03-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_plantsgallery_ar_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantsgallery',
            options={'verbose_name_plural': 'Plant Galleries'},
        ),
    ]
