# Generated by Django 4.0.3 on 2022-03-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='post_loc',
        ),
    ]
