# Generated by Django 4.0.3 on 2022-03-31 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_location_post_loc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
